/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-31 08:12:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class confirm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/mypage/menubar.jsp", Long.valueOf(1572506441787L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1572496681702L));
    _jspx_dependants.put("jar:file:/E:/final/Semi_LF/web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.container {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\twidth: 1280px;\r\n");
      out.write("\tmin-width: 1280px;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\tmin-height: 800px;\r\n");
      out.write("\tpadding-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".confirm_area {\r\n");
      out.write("    /* border: 1px solid black; */\r\n");
      out.write("    width: 500px;\r\n");
      out.write("    height: 500px;\r\n");
      out.write("    /* margin: 0 auto; */\r\n");
      out.write("    margin-left: 470px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".confirm_area h2 {\r\n");
      out.write("\tmargin-top: 180px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #3e3e3e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".confirm_area h3 {\r\n");
      out.write("\tcolor: #888888;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".confirm_area h4 {\r\n");
      out.write("\tcolor: #888888;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".emailInput {\r\n");
      out.write("\tmin-width: 330px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".confirmBtn {\r\n");
      out.write("\tbackground: #3030e4;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    margin-left: -3px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".emailText {\r\n");
      out.write("\tmin-width: 330px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sendConfirmMail {\r\n");
      out.write("\tbackground: #3030e4;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    margin-left: -3px;\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/css/mypage/confirm.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mypage/menubar.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/css/common/reset.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/js/mypage/menubar.js\" ></script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/*\r\n");
      out.write("html5doctor.com Reset Stylesheet\r\n");
      out.write("v1.6.1\r\n");
      out.write("Last Updated: 2010-09-17\r\n");
      out.write("Author: Richard Clark - http://richclarkdesign.com\r\n");
      out.write("Twitter: @rich_clark\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("html, body, div, span, object, iframe,\r\n");
      out.write("h1, h2, h3, h4, h5, h6, p, blockquote, pre,\r\n");
      out.write("abbr, address, cite, code,\r\n");
      out.write("del, dfn, em, img, ins, kbd, q, samp,\r\n");
      out.write("small, strong, sub, sup, var,\r\n");
      out.write("b, i,\r\n");
      out.write("dl, dt, dd, ol, ul, li,\r\n");
      out.write("fieldset, form, label, legend,\r\n");
      out.write("table, caption, tbody, tfoot, thead, tr, th, td,\r\n");
      out.write("article, aside, canvas, details, figcaption, figure,\r\n");
      out.write("footer, header, hgroup, menu, nav, section, summary,\r\n");
      out.write("time, mark, audio, video {\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    border:0;\r\n");
      out.write("    outline:0;\r\n");
      out.write("    font-size:100%;\r\n");
      out.write("    vertical-align:baseline;\r\n");
      out.write("    background:transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    line-height:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article,aside,details,figcaption,figure,\r\n");
      out.write("footer,header,hgroup,menu,nav,section {\r\n");
      out.write("    display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("    list-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote, q {\r\n");
      out.write("    quotes:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote:before, blockquote:after,\r\n");
      out.write("q:before, q:after {\r\n");
      out.write("    content:'';\r\n");
      out.write("    content:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    font-size:100%;\r\n");
      out.write("    vertical-align:baseline;\r\n");
      out.write("    background:transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change colours to suit your needs */\r\n");
      out.write("ins {\r\n");
      out.write("    background-color:#ff9;\r\n");
      out.write("    color:#000;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change colours to suit your needs */\r\n");
      out.write("mark {\r\n");
      out.write("    background-color:#ff9;\r\n");
      out.write("    color:#000;\r\n");
      out.write("    font-style:italic;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("del {\r\n");
      out.write("    text-decoration: line-through;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("abbr[title], dfn[title] {\r\n");
      out.write("    border-bottom:1px dotted;\r\n");
      out.write("    cursor:help;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    border-spacing:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change border colour to suit your needs */\r\n");
      out.write("hr {\r\n");
      out.write("    display:block;\r\n");
      out.write("    height:1px;\r\n");
      out.write("    border:0;  \r\n");
      out.write("    border-top:1px solid #cccccc;\r\n");
      out.write("    margin:1em 0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, select {\r\n");
      out.write("    vertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    line-height: 60px;\r\n");
      out.write("    margin-top: 6px;\r\n");
      out.write("    /* background: #dadada; */\r\n");
      out.write("    /* border-radius: 10px; */\r\n");
      out.write("    border-left: 1px solid #dadada;\r\n");
      out.write("    /* border-bottom: 1px solid #dadada; */\r\n");
      out.write("    box-shadow: 1px 1px 5px grey;\r\n");
      out.write("    border-radius: 0 0 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li:hover {\r\n");
      out.write("\tbackground: #4343e6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li:hover a {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("    display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li.active a {\r\n");
      out.write("\tbackground: #4343e6;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mpTitle {\r\n");
      out.write("\tmargin-top: 45px;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    border-bottom: 2px solid #afafaf;\r\n");
      out.write("    width: 1080px;\r\n");
      out.write("    margin-left: 200px;\r\n");
      out.write("    color: #484848;\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mpTitle span {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\tfont-family: \"Nanum Gothic\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: \"Nanum Gothic\", sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<h2 class=\"mpTitle\"><span>MY PAGE</span></h2>\r\n");
      out.write("\r\n");
      out.write("<ul class=\"mypageMenu\">   \r\n");
      out.write("\t<li><a href=\"views/member/MainPag.jsp\">메인 페이지</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myConfirm.bo\">정보수정</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myOrder.bo\">주문/배송</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myBasket.bo\">장바구니</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myReview.bo\">나의 리뷰</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/seller/SellerRegist.jsp\">판매자 등록</a></li>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 여기 에러나면 주석해서 테스트 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<!-- 여기까지 추가함 -->\r\n");
      out.write("\t\r\n");
      out.write("</ul>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"confirm_area\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<h2>이메일 인증</h2>\r\n");
      out.write("\t\t\t<h3>개인정보 보호를 위해 이메일 인증을 해주세요.</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"emailText\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"sendConfirmMail\" value=\"인증메일전송\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"emailInput\" placeholder=\"인증번호를 입력해주세요.\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"확인\" class=\"confirmBtn\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/js/mypage/confirm.js\" ></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
