/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-31 07:22:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import LF.member.model.vo.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1572496681702L));
    _jspx_dependants.put("jar:file:/E:/final/Semi_LF/web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/E:/final/Semi_LF/web/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/views/mypage/./menubar.jsp", Long.valueOf(1572506441787L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("LF.member.model.vo");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mypage/main.css\" />\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".container {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\twidth: 1280px;\r\n");
      out.write("\tmin-width: 1280px;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\tmin-height: 800px;\r\n");
      out.write("\tpadding-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea {\r\n");
      out.write("   min-width: 320px;\r\n");
      out.write("    min-height: 195px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(1) {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 23px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(2) {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".nameArea > span:nth-child(2) a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #2c2cff;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(3) {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    color: #5d5d5d;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    border-bottom: 2px solid #929292;\r\n");
      out.write("    padding-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea img {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(4) {\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin-top: 40px;\r\n");
      out.write("    /* margin-right: 75px; */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea .number {\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".infoArea {\r\n");
      out.write("    min-height: 200px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    margin-left: 590px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".infoArea ul li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("    width: 160px;\r\n");
      out.write("    height: 190px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    \r\n");
      out.write("    background: #fff;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: 35px;\r\n");
      out.write("    background-position: 10px 10px;\r\n");
      out.write("    \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    \r\n");
      out.write("    box-shadow: 4px 4px 10px 1px #868686;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(1) {\r\n");
      out.write("\tbackground-image: url(./images/order.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(2) {\r\n");
      out.write("\tbackground-image: url(./images/cart.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(3) {\r\n");
      out.write("\tbackground-image: url(./images/review.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(4) {\r\n");
      out.write("\tbackground-image: url(./images/qna.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".infoArea ul li span:nth-child(1) {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 19px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-left: 59px;\r\n");
      out.write("}\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li span:nth-child(2) {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("    margin-top: 88px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".orderListArea, .cartListArea {\r\n");
      out.write("\twidth: 1015px;\r\n");
      out.write("    border: 1px solid #cccccc;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cartListArea {\r\n");
      out.write("    margin-left: 230px;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write(".orderListArea table, .cartListArea table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr th, .cartListArea table tr th {\r\n");
      out.write("\tbackground: #cccccc;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr td, .cartListArea table tr td {\r\n");
      out.write("\tborder-bottom: 1px solid #cccccc;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr td:nth-child(1), .cartListArea table tr td:nth-child(1) {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr th:nth-child(1), .cartListArea table tr th:nth-child(1) {\r\n");
      out.write("\twidth:45%\r\n");
      out.write("}\r\n");
      out.write(".orderListArea table tr th:nth-child(2), .cartListArea table tr th:nth-child(2){\r\n");
      out.write("\twidth:20%;\r\n");
      out.write("}\r\n");
      out.write(".orderListArea table tr th:nth-child(3), .cartListArea table tr th:nth-child(3){\r\n");
      out.write("\twidth:20%;\r\n");
      out.write("}\r\n");
      out.write(".orderListArea table tr th:nth-child(4), .cartListArea table tr th:nth-child(4) {\r\n");
      out.write("\twidth:15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 추가 */\r\n");
      out.write(".listTitle {\r\n");
      out.write("\twidth: 1015px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 230px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listTitle span a {\r\n");
      out.write("\tcolor: #2c2cff;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cartListArea .deleteBtn {\r\n");
      out.write("\tborder: 1px solid #d8d8d8;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 80px;\r\n");
      out.write("}\r\n");
      out.write("/* 추가 */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mypage/menubar.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/css/common/reset.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/js/mypage/menubar.js\" ></script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/*\r\n");
      out.write("html5doctor.com Reset Stylesheet\r\n");
      out.write("v1.6.1\r\n");
      out.write("Last Updated: 2010-09-17\r\n");
      out.write("Author: Richard Clark - http://richclarkdesign.com\r\n");
      out.write("Twitter: @rich_clark\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("html, body, div, span, object, iframe,\r\n");
      out.write("h1, h2, h3, h4, h5, h6, p, blockquote, pre,\r\n");
      out.write("abbr, address, cite, code,\r\n");
      out.write("del, dfn, em, img, ins, kbd, q, samp,\r\n");
      out.write("small, strong, sub, sup, var,\r\n");
      out.write("b, i,\r\n");
      out.write("dl, dt, dd, ol, ul, li,\r\n");
      out.write("fieldset, form, label, legend,\r\n");
      out.write("table, caption, tbody, tfoot, thead, tr, th, td,\r\n");
      out.write("article, aside, canvas, details, figcaption, figure,\r\n");
      out.write("footer, header, hgroup, menu, nav, section, summary,\r\n");
      out.write("time, mark, audio, video {\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    border:0;\r\n");
      out.write("    outline:0;\r\n");
      out.write("    font-size:100%;\r\n");
      out.write("    vertical-align:baseline;\r\n");
      out.write("    background:transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    line-height:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article,aside,details,figcaption,figure,\r\n");
      out.write("footer,header,hgroup,menu,nav,section {\r\n");
      out.write("    display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("    list-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote, q {\r\n");
      out.write("    quotes:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote:before, blockquote:after,\r\n");
      out.write("q:before, q:after {\r\n");
      out.write("    content:'';\r\n");
      out.write("    content:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    font-size:100%;\r\n");
      out.write("    vertical-align:baseline;\r\n");
      out.write("    background:transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change colours to suit your needs */\r\n");
      out.write("ins {\r\n");
      out.write("    background-color:#ff9;\r\n");
      out.write("    color:#000;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change colours to suit your needs */\r\n");
      out.write("mark {\r\n");
      out.write("    background-color:#ff9;\r\n");
      out.write("    color:#000;\r\n");
      out.write("    font-style:italic;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("del {\r\n");
      out.write("    text-decoration: line-through;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("abbr[title], dfn[title] {\r\n");
      out.write("    border-bottom:1px dotted;\r\n");
      out.write("    cursor:help;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    border-spacing:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change border colour to suit your needs */\r\n");
      out.write("hr {\r\n");
      out.write("    display:block;\r\n");
      out.write("    height:1px;\r\n");
      out.write("    border:0;  \r\n");
      out.write("    border-top:1px solid #cccccc;\r\n");
      out.write("    margin:1em 0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, select {\r\n");
      out.write("    vertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    line-height: 60px;\r\n");
      out.write("    margin-top: 6px;\r\n");
      out.write("    /* background: #dadada; */\r\n");
      out.write("    /* border-radius: 10px; */\r\n");
      out.write("    border-left: 1px solid #dadada;\r\n");
      out.write("    /* border-bottom: 1px solid #dadada; */\r\n");
      out.write("    box-shadow: 1px 1px 5px grey;\r\n");
      out.write("    border-radius: 0 0 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li:hover {\r\n");
      out.write("\tbackground: #4343e6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li:hover a {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("    display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li.active a {\r\n");
      out.write("\tbackground: #4343e6;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mpTitle {\r\n");
      out.write("\tmargin-top: 45px;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    border-bottom: 2px solid #afafaf;\r\n");
      out.write("    width: 1080px;\r\n");
      out.write("    margin-left: 200px;\r\n");
      out.write("    color: #484848;\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mpTitle span {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\tfont-family: \"Nanum Gothic\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: \"Nanum Gothic\", sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<h2 class=\"mpTitle\"><span>MY PAGE</span></h2>\r\n");
      out.write("\r\n");
      out.write("<ul class=\"mypageMenu\">   \r\n");
      out.write("\t<li><a href=\"views/member/MainPag.jsp\">메인 페이지</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myConfirm.bo\">정보수정</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myOrder.bo\">주문/배송</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myBasket.bo\">장바구니</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myReview.bo\">나의 리뷰</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/seller/SellerRegist.jsp\">판매자 등록</a></li>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 여기 에러나면 주석해서 테스트 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<!-- 여기까지 추가함 -->\r\n");
      out.write("\t\r\n");
      out.write("</ul>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"nameArea\">\r\n");
      out.write("\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customerVo.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myConfirm.bo\">[ 회원정보수정 ]</a></span>\r\n");
      out.write("\t\t\t\t<span>가입일자&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customerVo.joinDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span><span class=\"number comma\" data-count=\"4800\"></span>원</span>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/coins.png\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"infoArea\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"Order\">\r\n");
      out.write("\t\t\t\t\t\t<span>주문배송</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.o_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"Basket\">\r\n");
      out.write("\t\t\t\t\t\t<span>장바구니</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.b_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"Review\">\r\n");
      out.write("\t\t\t\t\t\t<span>나의 리뷰</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.r_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"Qna\">\r\n");
      out.write("\t\t\t\t\t\t<span>문의 내역</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.q_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"listTitle\">최근 주문내역<span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myOrder.bo\">[ 바로가기 ]</a></span></div>\r\n");
      out.write("\t\t\t<div class=\"orderListArea\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상품명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>수량</th>\r\n");
      out.write("\t\t\t\t\t\t<th>판매자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>주문일자</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"listTitle\">최근 장바구니<span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myCart.bo\">[ 바로가기 ]</a></span></div>\r\n");
      out.write("\t\t\t<div class=\"cartListArea\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상품명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>수량</th>\r\n");
      out.write("\t\t\t\t\t\t<th>판매자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>삭제</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<input type=\"hidden\" class=\"flag\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flag }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/js/mypage/main.js\" ></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/mypage/main.jsp(272,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /views/mypage/main.jsp(272,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.pName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.scount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.sale_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /views/mypage/main.jsp(296,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("list");
      // /views/mypage/main.jsp(296,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basketList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.pName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td><input type=\"button\" value=\"삭제\" class=\"deleteBtn\" data-bId=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.basketId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /></td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
