/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-31 05:33:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import LF.member.model.vo.*;
import LF.member.model.vo.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1572496681702L));
    _jspx_dependants.put("jar:file:/E:/final/Semi_LF/web/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/E:/final/Semi_LF/web/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/views/mypage/./menubar.jsp", Long.valueOf(1572499834651L));
    _jspx_dependants.put("/views/mypage/./../common/menubar.jsp", Long.valueOf(1572499355127L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("LF.member.model.vo");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mypage/main.css\" />\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".container {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\twidth: 1280px;\r\n");
      out.write("\tmin-width: 1280px;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\tmin-height: 800px;\r\n");
      out.write("\tpadding-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea {\r\n");
      out.write("   min-width: 320px;\r\n");
      out.write("    min-height: 195px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(1) {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 23px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(2) {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".nameArea > span:nth-child(2) a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #2c2cff;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(3) {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    color: #5d5d5d;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    border-bottom: 2px solid #929292;\r\n");
      out.write("    padding-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea img {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea > span:nth-child(4) {\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin-top: 40px;\r\n");
      out.write("    /* margin-right: 75px; */\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameArea .number {\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".infoArea {\r\n");
      out.write("    min-height: 200px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    margin-left: 590px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".infoArea ul li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("    width: 160px;\r\n");
      out.write("    height: 190px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    \r\n");
      out.write("    background: #fff;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: 35px;\r\n");
      out.write("    background-position: 10px 10px;\r\n");
      out.write("    \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    \r\n");
      out.write("    box-shadow: 4px 4px 10px 1px #868686;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(1) {\r\n");
      out.write("\tbackground-image: url(./images/order.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(2) {\r\n");
      out.write("\tbackground-image: url(./images/cart.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(3) {\r\n");
      out.write("\tbackground-image: url(./images/review.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li:nth-child(4) {\r\n");
      out.write("\tbackground-image: url(./images/qna.png);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".infoArea ul li span:nth-child(1) {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 19px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-left: 59px;\r\n");
      out.write("}\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".infoArea ul li span:nth-child(2) {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("    margin-top: 88px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 수정 */\r\n");
      out.write(".orderListArea, .cartListArea {\r\n");
      out.write("\twidth: 1015px;\r\n");
      out.write("    border: 1px solid #cccccc;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cartListArea {\r\n");
      out.write("    margin-left: 230px;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("/* 수정 */\r\n");
      out.write("\r\n");
      out.write(".orderListArea table, .cartListArea table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr th, .cartListArea table tr th {\r\n");
      out.write("\tbackground: #cccccc;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr td, .cartListArea table tr td {\r\n");
      out.write("\tborder-bottom: 1px solid #cccccc;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr td:nth-child(1), .cartListArea table tr td:nth-child(1) {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderListArea table tr th:nth-child(1), .cartListArea table tr th:nth-child(1) {\r\n");
      out.write("\twidth:45%\r\n");
      out.write("}\r\n");
      out.write(".orderListArea table tr th:nth-child(2), .cartListArea table tr th:nth-child(2){\r\n");
      out.write("\twidth:20%;\r\n");
      out.write("}\r\n");
      out.write(".orderListArea table tr th:nth-child(3), .cartListArea table tr th:nth-child(3){\r\n");
      out.write("\twidth:20%;\r\n");
      out.write("}\r\n");
      out.write(".orderListArea table tr th:nth-child(4), .cartListArea table tr th:nth-child(4) {\r\n");
      out.write("\twidth:15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 추가 */\r\n");
      out.write(".listTitle {\r\n");
      out.write("\twidth: 1015px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 230px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listTitle span a {\r\n");
      out.write("\tcolor: #2c2cff;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cartListArea .deleteBtn {\r\n");
      out.write("\tborder: 1px solid #d8d8d8;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 80px;\r\n");
      out.write("}\r\n");
      out.write("/* 추가 */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<div class=\"container\" >\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mypage/menubar.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/css/common/reset.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/js/mypage/menubar.js\" ></script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/*\r\n");
      out.write("html5doctor.com Reset Stylesheet\r\n");
      out.write("v1.6.1\r\n");
      out.write("Last Updated: 2010-09-17\r\n");
      out.write("Author: Richard Clark - http://richclarkdesign.com\r\n");
      out.write("Twitter: @rich_clark\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("html, body, div, span, object, iframe,\r\n");
      out.write("h1, h2, h3, h4, h5, h6, p, blockquote, pre,\r\n");
      out.write("abbr, address, cite, code,\r\n");
      out.write("del, dfn, em, img, ins, kbd, q, samp,\r\n");
      out.write("small, strong, sub, sup, var,\r\n");
      out.write("b, i,\r\n");
      out.write("dl, dt, dd, ol, ul, li,\r\n");
      out.write("fieldset, form, label, legend,\r\n");
      out.write("table, caption, tbody, tfoot, thead, tr, th, td,\r\n");
      out.write("article, aside, canvas, details, figcaption, figure,\r\n");
      out.write("footer, header, hgroup, menu, nav, section, summary,\r\n");
      out.write("time, mark, audio, video {\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    border:0;\r\n");
      out.write("    outline:0;\r\n");
      out.write("    font-size:100%;\r\n");
      out.write("    vertical-align:baseline;\r\n");
      out.write("    background:transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    line-height:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article,aside,details,figcaption,figure,\r\n");
      out.write("footer,header,hgroup,menu,nav,section {\r\n");
      out.write("    display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("    list-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote, q {\r\n");
      out.write("    quotes:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote:before, blockquote:after,\r\n");
      out.write("q:before, q:after {\r\n");
      out.write("    content:'';\r\n");
      out.write("    content:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    font-size:100%;\r\n");
      out.write("    vertical-align:baseline;\r\n");
      out.write("    background:transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change colours to suit your needs */\r\n");
      out.write("ins {\r\n");
      out.write("    background-color:#ff9;\r\n");
      out.write("    color:#000;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change colours to suit your needs */\r\n");
      out.write("mark {\r\n");
      out.write("    background-color:#ff9;\r\n");
      out.write("    color:#000;\r\n");
      out.write("    font-style:italic;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("del {\r\n");
      out.write("    text-decoration: line-through;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("abbr[title], dfn[title] {\r\n");
      out.write("    border-bottom:1px dotted;\r\n");
      out.write("    cursor:help;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    border-spacing:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* change border colour to suit your needs */\r\n");
      out.write("hr {\r\n");
      out.write("    display:block;\r\n");
      out.write("    height:1px;\r\n");
      out.write("    border:0;  \r\n");
      out.write("    border-top:1px solid #cccccc;\r\n");
      out.write("    margin:1em 0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, select {\r\n");
      out.write("    vertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    line-height: 60px;\r\n");
      out.write("    margin-top: 6px;\r\n");
      out.write("    /* background: #dadada; */\r\n");
      out.write("    /* border-radius: 10px; */\r\n");
      out.write("    border-left: 1px solid #dadada;\r\n");
      out.write("    /* border-bottom: 1px solid #dadada; */\r\n");
      out.write("    box-shadow: 1px 1px 5px grey;\r\n");
      out.write("    border-radius: 0 0 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li:hover {\r\n");
      out.write("\tbackground: #4343e6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li:hover a {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("    display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu li.active a {\r\n");
      out.write("\tbackground: #4343e6;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mpTitle {\r\n");
      out.write("\tmargin-top: 45px;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    border-bottom: 2px solid #afafaf;\r\n");
      out.write("    width: 1080px;\r\n");
      out.write("    margin-left: 200px;\r\n");
      out.write("    color: #484848;\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mpTitle span {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\tfont-family: \"Nanum Gothic\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: \"Nanum Gothic\", sans-serif !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div style=\"display:none\">");
      out.write('\r');
      out.write('\n');

	Customer loginUser = (Customer)session.getAttribute("loginUser");
	Seller sellerUser = (Seller)session.getAttribute("sellerUser");
	Admin adminUser = (Admin)session.getAttribute("adminUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\"> \r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/css/lightslider.min.css\"/>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/js/lightslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.headerNavi{\t\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\tborder-radius:5px;\r\n");
      out.write("\t\twidth:auto;\r\n");
      out.write("\t\theight:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn {\r\n");
      out.write("  \t\tdisplay: inline-block;\r\n");
      out.write("  \t\toutline: none;\r\n");
      out.write("  \t\tline-height: 40px;\r\n");
      out.write("  \t\tpadding: 0 30px;\r\n");
      out.write("  \t\tfont-size: .8em;\r\n");
      out.write("  \t\ttext-align: center;\r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("  \t\tfont-weight: 500;\r\n");
      out.write("  \t\tcursor: pointer;\r\n");
      out.write("  \t\t-webkit-transition: all 0.3s ease 0s;\r\n");
      out.write("  \t\t-moz-transition: all 0.3s ease 0s;\r\n");
      out.write("  \t\t-o-transition: all 0.3s ease 0s;\r\n");
      out.write("  \t\ttransition: all 0.3s ease 0s;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.radius {\r\n");
      out.write(" \t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.medium {\r\n");
      out.write("  \t\tline-height: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.info {\r\n");
      out.write("  \t\tcolor: #fff;\r\n");
      out.write("  \t\tbackground: #38a4ff;\r\n");
      out.write("  \t\tborder: 1px solid transparent;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.circle {\r\n");
      out.write("  \t\tborder-radius: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menuBtn{\r\n");
      out.write("\t\tbackground:url('");
      out.print(request.getContextPath());
      out.write("/images/menubtn.png') no-repeat;\r\n");
      out.write("\t\tbackground-size: 80%; \r\n");
      out.write("\t\tbackground-repeat: no-repeat; \r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t\tborder: 0px;\r\n");
      out.write("\t\theight: 75px;\r\n");
      out.write("\t\twidth : 75px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#inlineUl li{\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rightMenu{\r\n");
      out.write("\t\talign:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menu{\r\n");
      out.write("\t\twidth: 250px; \r\n");
      out.write("\t\theight:calc(100% - 110px); \r\n");
      out.write("\t\tposition: fixed; \r\n");
      out.write("\t\ttop: 110px; \r\n");
      out.write("\t\tleft: -320px; \r\n");
      out.write("\t\tz-index: 1055;\r\n");
      out.write("\t\tbackground-color: #eee; \r\n");
      out.write("\t\tfont-size:1.2em;\r\n");
      out.write("\t\ttransition: All 0.2s ease;\r\n");
      out.write("\t\toverflow-x:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#menu.open{\r\n");
      out.write("\t\tleft:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.material-icons.md-25{\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tvertical-align:bottom;\r\n");
      out.write("\t}\r\n");
      out.write("\t.linkSpan{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t    top: 1px;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    font-style: normal;\r\n");
      out.write("   \t\tfont-weight: 400;\r\n");
      out.write("\t    line-height: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t.linkC{\r\n");
      out.write("\t\tpadding: 12px 8px 12px 16px;\r\n");
      out.write("\t    font-size: 1.1em;\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t    color: #333;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t    transition: .3s;\r\n");
      out.write("\t}\r\n");
      out.write("\t.aline{\r\n");
      out.write("\t\tborder-bottom: 1px solid #444;\r\n");
      out.write("\t}\r\n");
      out.write("\t.table-borderless td{\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tmargin-bottom:5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-body td{\r\n");
      out.write("\t\ttext-align:left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btnSize{\r\n");
      out.write("\t\talign:right; \r\n");
      out.write("\t\tmax-width:120px; \r\n");
      out.write("\t\tmax-height:42px;\r\n");
      out.write("\t\tmin-width:120px;\r\n");
      out.write("\t\tmin-height:42px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- header역할을 하며 로그인, 회원가입, 메뉴바를 열수 있는 버튼을 생성 -->\r\n");
      out.write("\t<div class=\"navbar navbar-expand-sm bg-light navbar-dark fixed-top row\" id=\"headerDiv\" style=\"width:1500px; max-height:100px; z-index:1055; float:top;\" >\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-1\" align=\"left\" >\r\n");
      out.write("\t\t\t<input id=\"menuBtn\" type=\"button\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-8\" align=\"center\">\r\n");
      out.write("\t\t\t<img id=\"logo\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" height='75' width=\"300\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-3\" id=\"rightMenu\" style=\"min-width:500px;\">\r\n");
      out.write("\t\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"inlineUl\">\r\n");
      out.write("\t\t\t\t\t<li><button id=\"loginBtn\" class=\"genric-btn info circle btnSize\" type=\"button\"  data-toggle=\"modal\" data-target=\"#loginModal\">로그인</button></li>\r\n");
      out.write("\t\t\t\t\t<li><button id=\"signUpBtn\" class=\"genric-btn info circle btnSize\" type=\"button\" data-toggle=\"modal\" data-target=\"#signupModal\">회원가입</button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"inlineUl\">\r\n");
      out.write("\t\t\t\t\t<li style=\"display:inline-block; vertical-align:middle\">");
      out.print(loginUser.getUserName() );
      out.write("님 환영합니다.</li>\r\n");
      out.write("\t\t\t\t\t<li><button id=\"logoutBtn\" class=\"genric-btn info circle btnSize\" type=\"button\">로그아웃</button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 슬라이드 형식으로 버튼 클릭시 도출되는 메뉴바 -->\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/member/MainPag.jsp\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">home</i></span>&nbsp;&nbsp;Home</a>\r\n");
      out.write("\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"#loginBtn\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;My Page</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
} else if(loginUser.getGroupNum().equals("1")) {
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"/Semi_LF/myMain.bo\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;My Page</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
} else if(loginUser.getGroupNum().equals("2")) {
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"/Semi_LF/myMain.bo\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;My Page</a>\r\n");
      out.write("\t\t");
} else if(loginUser.getGroupNum().equals("3")){
      out.write("\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/cuInfo.ad?currentPage=1\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;Admin Page</a>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t<a href=\"/Semi_LF/list.po?cate=0\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">add_shopping_cart</i></span>&nbsp;&nbsp;상품 게시판</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">shopping_basket</i></span>&nbsp;&nbsp;장바구니</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">shopping_cart</i></span>&nbsp;&nbsp;HOME</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">https</i></span>&nbsp;&nbsp;HOME</a>\r\n");
      out.write("\t\t<a href=\"/Semi_LF/list.fo\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">question_answer</i></span>&nbsp;&nbsp;고객센터</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/login.me\" onsubmit=\"return loginValidate();\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-dialog-centered\" style=\"width: 400px;\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 30px; text-align:center;\">\r\n");
      out.write("\t\t\t\t\t<!-- <form id=\"loginInfo\"> -->\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table-borderless\" style=\"display:inline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"loginId\" name=\"loginId\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"loginPwd\" name=\"loginPwd\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=2 align=\"right\"><a href=\"#\">아이디/비밀번호 찾기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("<!-- \t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal footer -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"loginConnect\" type=\"submit\" class=\"btn btn-success\">로그인</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\" id=\"closeLogin\">닫기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 회원가입 모달 -->\r\n");
      out.write("\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"signupModal\" tabindex=\"-1\" role=\"dialog\" style=\"margin-top:30px;\">\r\n");
      out.write("\t\t<form id=\"signupForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/signup.me\" onsubmit=\"return signValidate();\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-dialog-centered modal-lg\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" >회원가입</h4>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" id=\"closeSignup\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 10px; text-align:center;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table-borderless\"  style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"signupId\" name=\"signupId\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width:10px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><button type=\"button\" onclick=\"idCheck();\">중복체크</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"signupPwd\" name=\"signupPwd\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>비밀번호 재확인&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"signupPwd2\" name=\"signupPwd2\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=2 style=\"font-size:11px; vertical-align:bottom;\"><p style=\"margin-top:10px;\" id=\"matchingPwd\"></p></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"userName\" name=\"userName\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"address1\" name=\"address1\" placeholder=\"우편번호\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><button type=\"button\" onclick=\"addressFind()\">주소 검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=4><input type=\"text\" class=\"form-control\" id=\"address2\" name=\"address2\" placeholder=\"주소\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=4><input type=\"text\" class=\"form-control\" id=\"address3\" name=\"address3\" placeholder=\"상세주소\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>휴대전화</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"phoneNum\" name=\"phoneNum\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"emailAddress\" name=\"emailAddress\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>@</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td id=\"hiddenEmail\"></td> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"display:inline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"emailLog\" id=\"emailLog\" class=\"custom-select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\" selected>-- 선택 --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal footer -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"signupConnect\" type=\"submit\" class=\"btn btn-success\">가입</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\" id=\"closeSign\">닫기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#signupId\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 메뉴바 버튼 */\r\n");
      out.write("\t\t\t$(\"#menuBtn\").click(function() {\r\n");
      out.write("\t\t\t\tif ($(\"#menu\").hasClass(\"open\")) { //class에 open이 없을 시 open클래스 추가 있을 시 삭제\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").addClass(\"open\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 일반회원 버튼\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 판매자 버튼\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 관리자 버튼\r\n");
      out.write("\t\t\t$(\"#adminPage\").click(function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"../admin/adminMainPage.jsp\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 로그인 기능 */\r\n");
      out.write("\t\t\t// validate() 함수 작성하기(form태그가 submit되었을 때 실행 됨)\r\n");
      out.write("\t\t\tfunction loginValidate(){\r\n");
      out.write("\t\t\t\tif($(\"#userId\").val().trim().length==0){\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\t// return값이 false면 submit이 되지 않는다.\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#userPwd\").val().trim().length==0){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 회원가입 기능\r\n");
      out.write("\t\t\tfunction signValidate(){\r\n");
      out.write("\t\t\t\tif($(\"#signupId\").val().trim().length<=3){\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 4자 이상입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#signupId\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\t// return값이 false면 submit이 되지 않는다.\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(!$(\"#signupId\").is(\"readonly\")){\r\n");
      out.write("\t\t\t\t\talert(\"아이디 중복검사를 해주세요\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#signupPwd\").val().trim().length<=3){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#signupPwd\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 로그인을 안했을 시 MyPage를 누르면 로그인창이 열림\r\n");
      out.write("\t\t\t$(\"#MyPage\").click(function(){\r\n");
      out.write("\t\t\t\t$(\"#loginBtn\").click();\r\n");
      out.write("\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 로그인, 회원가입중 하나가 열려 있을 시 발동 (다른 모달 및 메뉴바를 없앤다.)\r\n");
      out.write("\t\t\t$(\"#loginBtn\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#menu\").hasClass(\"open\")){\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#signupModal\").hasClass(\"show\")){\r\n");
      out.write("\t\t\t\t\t$(\"#signupModal\").modal('hide');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#signupBtn\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#menu\").hasClass(\"open\")){\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#loginModal\").hasClass(\"show\")){\r\n");
      out.write("\t\t\t\t\t$(\"#loginModal\").modal('hide');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#matchingPwd\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 아이디 중복 체크\r\n");
      out.write("\t\tfunction idCheck(){\r\n");
      out.write("\t\t\tvar checkid = $(\"#signupId\").val();\r\n");
      out.write("\t\t\tconsole.log(checkid);\r\n");
      out.write("\t\t\tif(checkid == \"\" || checkid.length <4){\r\n");
      out.write("\t\t\t\talert(\"아이디를 4글자 이상으로 적어주세요\");\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/Semi_LF/checkid.me\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {checkid : checkid},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif(data == 1){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 사용중인 아이디입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#signupId\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#signupId\").focus();\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"사용 가능한 아이디입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#signupId\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호 일치 기능\r\n");
      out.write("\t\t$(\"#signupPwd2\").keyup(function(){\r\n");
      out.write("\t\t\tvar pwd1 = $(\"#signupPwd\").val();\r\n");
      out.write("\t\t\tvar pwd2 = $(\"#signupPwd2\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pwd1 != \"\" || pwd2 != \"\"){\r\n");
      out.write("                if(pwd1 == pwd2){\r\n");
      out.write("                    $(\"#matchingPwd\").text(\"비밀번호가 일치합니다.\").css(\"color\",\"blue\");\r\n");
      out.write("                    $(\"#matchingPwd\").show();\r\n");
      out.write("                }else{\r\n");
      out.write("                    $(\"#matchingPwd\").text(\"비밀번호가 일치하지 않습니다.\").css(\"color\",\"red\");;\r\n");
      out.write("                \t$(\"#matchingPwd\").show();\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(pwd1<=3){\r\n");
      out.write("\t\t\t\t$(\"#matchingPwd\").text(\"비밀번호를 4자 이상으로 적어주세요\").css(\"color\",\"red\");;\r\n");
      out.write("            \t$(\"#matchingPwd\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).click(function(event) { // 메뉴바를 제외한 부분 클릭시 메뉴바 닫힘\r\n");
      out.write("\t\t\t\tif (!($(\"#menu\").is(event.target)|| $(\"#menuBtn\").is(event.target)\r\n");
      out.write("\t\t\t\t\t|| $(\"#menu\").children().is(event.target) || $(\r\n");
      out.write("\t\t\t\t\t\t\"#childsBtn\").children().is(event.target))) {\r\n");
      out.write("\t\t\t\t\t\tif ($(\"#menu\").hasClass(\"open\")) { //class에 open이 없을 시 open클래스 추가 있을 시 삭제\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#logoutBtn\").click(function(){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/logout.me\";\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("\t\tfunction addressFind() {\r\n");
      out.write("\t\t\tnew daum.Postcode(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\t\t\tvar fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\t\t\tvar extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\t\t\tif (data.bname !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\tif (data.buildingName !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\tif (fullRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\tfullRoadAddr += extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('address1').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('address2').value = fullRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("<h2 class=\"mpTitle\"><span>MY PAGE</span></h2>\r\n");
      out.write("\r\n");
      out.write("<ul class=\"mypageMenu\">\r\n");
      out.write("\t\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myConfirm.bo\">정보수정</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myOrder.bo\">주문/배송</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myBasket.bo\">장바구니</a></li>\r\n");
      out.write("\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myReview.bo\">나의 리뷰</a></li>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 여기 에러나면 주석해서 테스트 -->\r\n");
      out.write("\t");
if(loginUser.getGroupNum().equals("1")) {
      out.write(" \r\n");
      out.write("\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/views/seller/SellerRegist.jsp\">판매자 등록</a></li>\r\n");
      out.write("\t");
}else if(loginUser.getGroupNum().equals("2")) {
      out.write("\t\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/sellerInfoMng.selr?fid=");
      out.print(sellerUser.getFid());
      out.write("\"><span>판매자 정보 관리</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/productMngList.prod?sid=");
      out.print(sellerUser.getSid());
      out.write("\"><span>판매 상품 관리</span></a></li> <!-- PrMngListServlet -->\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/reviewList.selr?sid=");
      out.print(sellerUser.getSid());
      out.write("\"><span>상품 리뷰 확인</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/sReport.selr?sid=");
      out.print(sellerUser.getSid());
      out.write("\"><span>주문 및 매출 관리</span></a></li>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t<!-- 여기까지 추가함 -->\r\n");
      out.write("\t\r\n");
      out.write("</ul>  \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"nameArea\">\r\n");
      out.write("\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customerVo.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myConfirm.bo\">[ 회원정보수정 ]</a></span>\r\n");
      out.write("\t\t\t\t<span>가입일자&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customerVo.joinDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span><span class=\"number comma\" data-count=\"4800\"></span>원</span>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/coins.png\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"infoArea\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"Order\">\r\n");
      out.write("\t\t\t\t\t\t<span>주문배송</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.o_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"Basket\">\r\n");
      out.write("\t\t\t\t\t\t<span>장바구니</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.b_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"Review\">\r\n");
      out.write("\t\t\t\t\t\t<span>나의 리뷰</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.r_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"Qna\">\r\n");
      out.write("\t\t\t\t\t\t<span>문의 내역</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number\" data-count=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCountVo.q_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"listTitle\">최근 주문내역<span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myOrder.bo\">[ 바로가기 ]</a></span></div>\r\n");
      out.write("\t\t\t<div class=\"orderListArea\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상품명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>수량</th>\r\n");
      out.write("\t\t\t\t\t\t<th>판매자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>주문일자</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"listTitle\">최근 장바구니<span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myCart.bo\">[ 바로가기 ]</a></span></div>\r\n");
      out.write("\t\t\t<div class=\"cartListArea\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상품명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>수량</th>\r\n");
      out.write("\t\t\t\t\t\t<th>판매자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>삭제</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<input type=\"hidden\" class=\"flag\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flag }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/js/mypage/main.js\" ></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/mypage/main.jsp(270,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /views/mypage/main.jsp(270,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.pName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.scount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.sale_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /views/mypage/main.jsp(294,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("list");
      // /views/mypage/main.jsp(294,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basketList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.pName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td><input type=\"button\" value=\"삭제\" class=\"deleteBtn\" data-bId=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.basketId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" /></td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
